sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t ramsteven/complex-docker -f ./client/Dockerfile.dev ./client


script: 
  - docker run -e CI=true ramsteven/complex-docker npm test

after_success:
  - docker build -t ramsteven/multi-client ./client
  - docker build -t ramsteven/multi-nginx ./nginx
  - docker build -t ramsteven/multi-server ./server
  - docker build -t ramsteven/multi-worker ./worker

# Log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID --password-stdin"

# Take those images and push them to the docker hub

  - docker push ramsteven/multi-client
  - docker push ramsteven/multi-nginx
  - docker push ramsteven/multi-server
  - docker push ramsteven/multi-worker